export default {
  'line-height': 'rem',
  'font-size': 'rem',
  'width': 'rem',
  'height': 'rem',
  'min-width': 'rem',
  'min-height': 'rem',
  'max-width': 'rem',
  'max-height': 'rem',
  'margin': 'rem',
  'margin-top': 'rem',
  'margin-right': 'rem',
  'margin-bottom': 'rem',
  'margin-left': 'rem',
  'padding': 'rem',
  'padding-top': 'rem',
  'padding-right': 'rem',
  'padding-bottom': 'rem',
  'padding-left': 'rem',
  'top': 'rem',
  'right': 'rem',
  'bottom': 'rem',
  'left': 'rem',
  'border-radius': 'rem',
}