export const FETCH_HOME_INFO = 'FETCH_HOME_INFO';
export const FINISHED_FETCH_HOME_INFO = 'FINISHED_FETCH_HOME_INFO';
export const ERROR_FETCH_HOME_INFO = 'ERROR_FETCH_HOME_INFO';

export const FETCH_ABOUT_INFO = 'FETCH_ABOUT_INFO';
export const FINISHED_FETCH_ABOUT_INFO = 'FINISHED_FETCH_ABOUT_INFO';
export const ERROR_FETCH_ABOUT_INFO = 'ERROR_FETCH_ABOUT_INFO';

export const FETCH_JOIN_INFO = 'FETCH_JOIN_INFO';
export const FINISHED_FETCH_JOIN_INFO = 'FINISHED_FETCH_JOIN_INFO';
export const ERROR_FETCH_JOIN_INFO = 'ERROR_FETCH_JOIN_INFO';

export const FETCH_TECH_LIST = 'FETCH_TECH_LIST';
export const FINISHED_FETCH_TECH_LIST = 'FINISHED_FETCH_TECH_LIST';
export const ERROR_FETCH_TECH_LIST = 'ERROR_FETCH_TECH_LIST';

export const FETCH_TECH_MAINS = 'FETCH_TECH_MAINS';
export const FINISHED_FETCH_TECH_MAINS = 'FINISHED_FETCH_TECH_MAINS';
export const ERROR_FETCH_TECH_MAINS = 'ERROR_FETCH_TECH_MAINS';

export const FETCH_TEAM_LIST = 'FETCH_TEAM_LIST';
export const FINISHED_FETCH_TEAM_LIST = 'FINISHED_FETCH_TEAM_LIST';
export const ERROR_FETCH_TEAM_LIST = 'ERROR_FETCH_TEAM_LIST';

export const FETCH_TEAM_ALL = 'FETCH_TEAM_ALL';
export const FINISHED_FETCH_TEAM_ALL = 'FINISHED_FETCH_TEAM_ALL';
export const ERROR_FETCH_TEAM_ALL = 'ERROR_FETCH_TEAM_ALL';

export const FETCH_TEAM_COUNT = 'FETCH_TEAM_COUNT';
export const FINISHED_FETCH_TEAM_COUNT = 'FINISHED_FETCH_TEAM_COUNT';
export const ERROR_FETCH_TEAM_COUNT = 'FETCH_TEAM_COUNT';

export const FETCH_TEAM_MEMBER = 'FETCH_TEAM_MEMBER';
export const FINISHED_FETCH_TEAM_MEMBER = 'FINISHED_FETCH_TEAM_MEMBER';
export const ERROR_FETCH_TEAM_MEMBER = 'ERROR_FETCH_TEAM_MEMBER';

export const FETCH_CLIENT_ALL = 'FETCH_CLIENT_ALL';
export const FINISHED_FETCH_CLIENT_ALL = 'FINISHED_FETCH_CLIENT_ALL';
export const ERROR_FETCH_CLIENT_ALL = 'ERROR_FETCH_CLIENT_ALL';

export const FETCH_CLIENT_LIST = 'FETCH_CLIENT_LIST';
export const FINISHED_FETCH_CLIENT_LIST = 'FINISHED_FETCH_CLIENT_LIST';
export const ERROR_FETCH_CLIENT_LIST = 'ERROR_FETCH_CLIENT_LIST';

export const FETCH_CLIENT_MAINS = 'FETCH_CLIENT_MAINS';
export const FINISHED_FETCH_CLIENT_MAINS = 'FINISHED_FETCH_CLIENT_MAINS';
export const ERROR_FETCH_CLIENT_MAINS = 'ERROR_FETCH_CLIENT_MAINS';

export const FETCH_CLIENT_PROJECT = 'FETCH_CLIENT_PROJECT';
export const FINISHED_FETCH_CLIENT_PROJECT = 'FINISHED_FETCH_CLIENT_PROJECT';
export const ERROR_FETCH_CLIENT_PROJECT = 'ERROR_FETCH_CLIENT_PROJECT';

export const FETCH_PROJECT_ALL = 'FETCH_PROJECT_ALL';
export const FINISHED_FETCH_PROJECT_ALL = 'FINISHED_FETCH_PROJECT_ALL';
export const ERROR_FETCH_PROJECT_ALL = 'ERROR_FETCH_PROJECT_ALL';

export const FETCH_PROJECT_MEMBER = 'FETCH_PROJECT_MEMBER';
export const FINISHED_FETCH_PROJECT_MEMBER = 'FINISHED_FETCH_PROJECT_MEMBER';
export const ERROR_FETCH_PROJECT_MEMBER = 'ERROR_FETCH_PROJECT_MEMBER';

export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FINISHED_FETCH_PROJECT = 'FINISHED_FETCH_PROJECT';
export const ERROR_FETCH_PROJECT = 'ERROR_FETCH_PROJECT';

export const FETCH_DOMAIN_LIST = 'FETCH_DOMAIN_LIST';
export const FINISHED_FETCH_DOMAIN_LIST = 'FINISHED_FETCH_DOMAIN_LIST';
export const ERROR_FETCH_DOMAIN_LIST = 'ERROR_FETCH_DOMAIN_LIST';

export const FETCH_DOMAIN_ALL = 'FETCH_DOMAIN_ALL';
export const FINISHED_FETCH_DOMAIN_ALL = 'FINISHED_FETCH_DOMAIN_ALL';
export const ERROR_FETCH_DOMAIN_ALL = 'ERROR_FETCH_DOMAIN_ALL';
